# -*- coding: utf-8 -*-
"""
  @Description
  @Author Chris
  @Date 2023/6/28
"""

MODEL_PATH = "../Model"
POLICY_MODEL_PATH = MODEL_PATH + "/PolicyModel.pth"
VALUE_MODEL_PATH = MODEL_PATH + "/ValueModel.pth"

CLASSICAL_SCHEDULING_STRATEGIES = ["FIFO", "FILO", "SPT", "LPT", "SRTPT", "LRTPT", "LOR", "MOR", "ERD"]
DYNAMICAL_SCHEDULING_STRATEGY = "DYNAMIC"
SCHEDULING_STRATEGIES = CLASSICAL_SCHEDULING_STRATEGIES + [DYNAMICAL_SCHEDULING_STRATEGY]

TASK_EVENT = 0
MACHINE_EVENT = 1
if __name__ == '__main__':
    pass
